spring:
  application:
    name: crud-spring
    cors:
      origins: 'http://localhost:4200'
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  file:
    name: logs/app.log
